### ISSUE TITLE
Port to npmjs

### ISSUE THREAD

**Issue by SpooN1337** [pushchris/backbone.marionette.subrouter#10]
Would it be possible to port this to npmjs for npm install please?

**Comment by pushchris** [comment]
@SpooN1337 I don't have any plans to port it over at this point but if you wanted to submitted a pull request with the port I would be happy to include it.

**Comment by jperasmus** [comment]
Sorry to jump in here, but isn't it as simple as running `npm publish` if you have an npm account already seeing that you already have a package.json file? The only thing that I can see is that you might need to update the name property to "backbone.marionette.subrouter".

https://docs.npmjs.com/getting-started/publishing-npm-packages

**Comment by pushchris** [comment]
@jperasmus I went ahead and submitted it to npm with the name "backbone.marionette.subrouter"

**Comment by jperasmus** [comment]
Brilliant, thank you very much!
